### ISSUE TITLE
DataTables 1.10.0-dev Compatibility

### ISSUE THREAD

**Issue by Xavina** [vpllan/jQuery.dataTables.oData#10]
Is this extension compatible with DataTables 1.10.0-dev version?

Thanks,

**Comment by vpllan** [comment]
Version 1.10.0-dev cannot be found in a list of official DataTables releases (https://github.com/DataTables/DataTables/releases).
However, this extension comes packed with version 1.10.0, so it should be compatible.

**Comment by Xavina** [comment]
The extension comes packed with version 1.9.4 at folder '\jQuery.dataTables.oData-master\media\js', am I right?

Where is the packet version with datatables 1.10.0 version?

**Comment by vpllan** [comment]
You are right. My bad. It comes with 1.9.4.
Extension works with both versions of DT. However, it behaves differently with DataTables 1.10.0 and shows 5 pages with 2 items per page instead of 1 page with 10 items as it should. 
The problem is on DT side (you may check that by excluding the extension). Even though the default value for a page length should be 10 (http://datatables.net/reference/option/pageLength) it uses the first value in the list (which in a given example is 2, so it shows 2 items per page).
